/// Flutter icons RequiredIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RequiredIcons
///      fonts:
///       - asset: fonts/RequiredIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class RequiredIcons {
  RequiredIcons._();

  static const _kFontFam = 'RequiredIcons';

  static const IconData user = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData email = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData mail = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData key = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData vpn_key = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData eye = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData eye_off = IconData(0xe806, fontFamily: _kFontFam);
}
